config/routes.rb
Rails.application.routes.draw do
  resources :subs
  root to: 'subs#new'

end

app/models/sub.rb
class Sub < ActiveRecord::Base
	validates :email, uniqueness: { message: "You're already subscribed. Thanks!"}
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
    message: "That email doesn't look right. Please try again." }
            
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :set_sub, only: [:show, :edit, :update, :destroy]

  # GET /subs
  # GET /subs.json
  def index
    @subs = Sub.all
  end

  # GET /subs/1
  # GET /subs/1.json
  def show
  end

  # GET /subs/new
  def new
    @sub = Sub.new
  end

  # GET /subs/1/edit
  def edit
  end

  # POST /subs
  # POST /subs.json
  def create
    @sub = Sub.new(sub_params)

    respond_to do |format|
      if @sub.save
        # format.html { redirect_to @sub, notice: 'Sub was successfully created.' }
        format.html { redirect_to @sub, notice: "Thanks! We'll be in touch soon." }
        format.json { render :show, status: :created, location: @sub }
      else
        format.html { render :new }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subs/1
  # PATCH/PUT /subs/1.json
  def update
    respond_to do |format|
      if @sub.update(sub_params)
        format.html { redirect_to @sub, notice: 'Sub was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub }
      else
        format.html { render :edit }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subs/1
  # DELETE /subs/1.json
  def destroy
    @sub.destroy
    respond_to do |format|
      format.html { redirect_to subs_url, notice: 'Sub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub
      @sub = Sub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_params
      params.require(:sub).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Kloudkeep Solutions</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="alert alert-success" id="email-exists">You're already subscribed.</p>
	<%= yield %>





</body>
</html>

app/views/subs/_form.html.erb
<%= form_for(@sub) do |f| %>
  <% if @sub.errors.any? %>
    <div id="error_explanation">
      <!-- <h2><%= pluralize(@sub.errors.count, "error") %> prohibited this sub from being saved:</h2>
 -->
      <ul>
      <% @sub.errors.each_with_index do |message, i| %>
        <li><%= message[1] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group form-inline">
    
    <%= f.email_field :email, class: "form-control", autofocus: true, required: true, placeholder: "Email address..." %>
    <%= f.submit "Subscribe", class: "btn btn-success" %>
  </div>
  
    
  </div>
<% end %>

app/views/subs/edit.html.erb
<h1>Editing sub</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub %> |
<%= link_to 'Back', subs_path %>

app/views/subs/new.html.erb
<!-- <h1>New sub</h1>
 -->
 <div class="site-wrapper">

       <div class="site-wrapper-inner">

         <div class="cover-container">

           

           <div class="inner cover">
             <h1 class="cover-heading">A place for all your stuff.</h1><br />
             <p class="">Get <strong>early access</strong> and <strong>infrequent updates</strong> by email.</p>
             <%= render 'form' %>
           </div>

           

         </div>

       </div>

     </div>

app/views/subs/show.html.erb
<p class="alert alert-success"><%= notice %></p>